package com.model;

import java.util.List;

/**
 * TCatelog generated by MyEclipse Persistence Tools
 */

public class TCatelog implements java.io.Serializable
{

	// Fields

	private Integer catelogId;

	private String catelogName;

	private String catelogMiaoshu;

	private String catelogDel;
	
	private List goodsList;

	// Constructors

	/** default constructor */
	public TCatelog()
	{
	}

	/** full constructor */
	public TCatelog(String catelogName, String catelogMiaoshu, String catelogDel)
	{
		this.catelogName = catelogName;
		this.catelogMiaoshu = catelogMiaoshu;
		this.catelogDel = catelogDel;
	}

	// Property accessors

	public Integer getCatelogId()
	{
		return this.catelogId;
	}

	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}

	public String getCatelogName()
	{
		return this.catelogName;
	}

	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}

	public String getCatelogMiaoshu()
	{
		return this.catelogMiaoshu;
	}

	public void setCatelogMiaoshu(String catelogMiaoshu)
	{
		this.catelogMiaoshu = catelogMiaoshu;
	}

	public String getCatelogDel()
	{
		return this.catelogDel;
	}

	public void setCatelogDel(String catelogDel)
	{
		this.catelogDel = catelogDel;
	}

	public List getGoodsList()
	{
		return goodsList;
	}

	public void setGoodsList(List goodsList)
	{
		this.goodsList = goodsList;
	}

}