package com.model;

/**
 * TJingpai generated by MyEclipse Persistence Tools
 */

public class TJingpai implements java.io.Serializable
{

	// Fields

	private Integer jingpaiId;

	private Integer jingpaiJiage;

	private Integer jingpaiGoodsId;

	private Integer jingpaiUserId;

	private String jingpaiShijian;

	private String del;
	
	private String jingpaiGoodsName;

	// Constructors

	/** default constructor */
	public TJingpai()
	{
	}

	/** full constructor */
	public TJingpai(Integer jingpaiJiage, Integer jingpaiGoodsId,
			Integer jingpaiUserId, String jingpaiShijian, String del)
	{
		this.jingpaiJiage = jingpaiJiage;
		this.jingpaiGoodsId = jingpaiGoodsId;
		this.jingpaiUserId = jingpaiUserId;
		this.jingpaiShijian = jingpaiShijian;
		this.del = del;
	}

	// Property accessors

	public Integer getJingpaiId()
	{
		return this.jingpaiId;
	}

	public void setJingpaiId(Integer jingpaiId)
	{
		this.jingpaiId = jingpaiId;
	}

	public Integer getJingpaiJiage()
	{
		return this.jingpaiJiage;
	}

	public void setJingpaiJiage(Integer jingpaiJiage)
	{
		this.jingpaiJiage = jingpaiJiage;
	}

	public Integer getJingpaiGoodsId()
	{
		return this.jingpaiGoodsId;
	}

	public void setJingpaiGoodsId(Integer jingpaiGoodsId)
	{
		this.jingpaiGoodsId = jingpaiGoodsId;
	}

	public Integer getJingpaiUserId()
	{
		return this.jingpaiUserId;
	}

	public void setJingpaiUserId(Integer jingpaiUserId)
	{
		this.jingpaiUserId = jingpaiUserId;
	}

	public String getJingpaiShijian()
	{
		return this.jingpaiShijian;
	}

	public void setJingpaiShijian(String jingpaiShijian)
	{
		this.jingpaiShijian = jingpaiShijian;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getJingpaiGoodsName()
	{
		return jingpaiGoodsName;
	}

	public void setJingpaiGoodsName(String jingpaiGoodsName)
	{
		this.jingpaiGoodsName = jingpaiGoodsName;
	}

}